version: "3"

env:
  COMPOSE_PROJECT_NAME: feature-sliced-example
  PROJECT_ID: 003
  DOCKER_BUILDKIT: 1

silent: true

tasks:
  default:
    cmds:
      - task --list

  init:
    desc: Инициализация проекта
    cmds:
      - task clean
      - task install
      - task start
      - task info

  clean:
    desc: Очистка контейнеров
    cmds:
      - docker-compose down --rmi local -v

  install:
    desc: Установка зависимостей
    cmds:
      - docker-compose run --no-deps --rm -T frontend npm install

  start:
    desc: Запуск проекта
    cmds:
      - docker-compose up -d

  restart:
    desc: Перезапуск проекта
    cmds:
      - task clean
      - task start
      - task info

  stop:
    desc: Остановка проекта
    cmds:
      - docker-compose stop

  lint:
    desc: Проверка кода
    cmds:
      - printf "\033[33m%s:\033[0m\n" 'ESLint'
      - docker-compose exec -T frontend npm run eslint
      - printf "\033[33m%s:\033[0m\n" 'Stylelint'
      - docker-compose exec -T frontend npm run stylelint

  cs-fix:
    desc: Форматирование кода
    cmds:
      - printf "\033[33m%s:\033[0m\n" 'ESLint'
      - docker-compose exec -T frontend npm run eslint:fix
      - printf "\033[33m%s:\033[0m\n" 'Stylelint'
      - docker-compose exec -T frontend npm run stylelint:fix

  ps:
    desc: Список запущенных контейнеров
    cmds:
      - docker-compose ps

  info:
    desc: Информация о проекте
    cmds:
      - echo "site - http://localhost:20${PROJECT_ID}"
