import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>
          <a href="https://nextjs.org/docs">Documentation &rarr;</a>
        </p>
      </main>
    </>
  );
};

export default Home;
